Разметка главной страницы
htmlacademy-adaptive/555-pink-23 pull request #2
Opened 2021-07-26 14:47 UTC by EtelBogen

2021-08-01 19:31 UTC, Manyaka requested changes

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +        <img class="page-header__logo-image" src="" width="74" height="23" alt="Логотип в виде слова PINK белого цвета">
Это функциональный альт, или надо описывать? Точку в конце добавь в любом случае.

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +          <span class="visually-hidden">Открыть меню</span>
точку, для паузы скрин ридера

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +        <div class="main-navigation__wrapper">
враппер зачем?

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +              <a href="https://htmlacademy.ru/intensive/adaptive">HTML Academy</a>
target blank, всегда, когда ссылки на внешние ресурсы, делаешь таргет бланк, есть идеи почему так?

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +      <div class="page-header__wrapper page-header__wrapper--index">
зачем див, да еще отличающийся от внутренних страниц?

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +          <h1 class="visually-hidden">Приложение PINK</h1>
точки ставь, во всех местах, которые скрин-ридер читает.

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +      <div class="page-header__wrapper page-header__wrapper--index">
лучше обернула бы навигацию и лого в враппер, тк как ты их верстать будешь?

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +        <section class="intro intro--index">
Зачем тут `section`? уже есть секция, которая выделена с помощью тега `header`.

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +          <p class="intro__header intro__header--index">Взгляните на жизнь иначе!</p>
текст вытащи из блока, он сам встанет куда надо, ты же добавила к нему модификатор (мод)

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +          <section class="intro__downloads">
Зачем секция внутри секции? Дивы же есть для выделения мелких блоков. Секция - для выделения крупных блоков.

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +            <a class="intro__downloads-link button">Скачать приложение</a>
href

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +        </section>
Руку бекграундом будешь делать?

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +    <main class="page-main page-main--index">
а что хочешь на main повесить, чтобы мод использовать?

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +        <ul class="information__advantages advantages-list">
тут начинается серая секция

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +          <h2 class="visually-hidden">Отзывы</h2>
h2 - это же заголовок секции, а не дива

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +          <ul class="reviews__list slider__list">
если слайдер делаешь через ul, то див - это уже лишняя обертка, всё прекрасно вешается на ul

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +          <ul class="reviews__list slider__list">
элемент не может одновременно принадлежать двум блокам

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +              </blockquote>
это самостоятельный блок

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +          </div>
ошибка, когда два блока на элементе

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +            </p>
параграф?

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +            <!-- Тут должна быть таблица, но я пока не поняла, как ее сделать -->
Может, появились идеи, как таблицу сделать таблицей? :)

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +          <h2 class="visually-hidden">Отзывы</h2>
поправь все аналогичные ошибки

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +          <р class="contacts__slogan">Остались вопросы?</p>
```suggestion
          <p class="contacts__slogan">Остались вопросы?</p>
```

кириллица, надо поменять на латинскую букву

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +          <p class="contacts__slogan">Свяжитесь с нами!</p>
Это больше похоже на 1 параграф с br

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +              </b>
```suggestion
              </p>
```
видимо хотела сделать жирным через теги

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +      <div class="page-footer__wrapper page-footer__wrapper--index">
уже есть враппер - footer

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +        <img class="page-footer__logo-image" width="145" height="40" src="" alt="Логотип в виде розовых очков и слова PINK черного цвета">
аналогично про альт сверху

2021-08-01 19:31 UTC, Manyaka commented on source/index.html
> +          <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive" aria-label="HTML Academy">HTML Academy</a>
а зачем тут  aria-label?

2021-08-01 19:49 UTC, EtelBogen commented on source/index.html
> +              <a href="https://htmlacademy.ru/intensive/adaptive">HTML Academy</a>
Чтобы не уводило с сайта посетителя. Открывается в новой вкладке, но он при этом остается на сайте.

2021-08-01 19:54 UTC, EtelBogen commented on source/index.html
> +        <img class="page-header__logo-image" src="" width="74" height="23" alt="Логотип в виде слова PINK белого цвета">
Функциональный на внутренних страниц, с них ведет на главную. Я хочу сделать описание на главной странице, на внутренних текст "На главную страницу сайта приложения PINK."

2021-08-01 20:01 UTC, Manyaka commented on source/index.html
> +        <img class="page-header__logo-image" src="" width="74" height="23" alt="Логотип в виде слова PINK белого цвета">
ну "слепому" человеку есть смысл в информации, что это логотип белыми буквами? Нет. Ему можно описать это как "главная страница сайта приложения Пинк."

2021-08-01 20:02 UTC, EtelBogen commented on source/index.html
> +        <div class="main-navigation__wrapper">
А это я ошиблась. Потому что смотрела на пример с лекций, но там навигация только центрируется. Я подумала, что мне надо в обертку и лого тоже, но на автомате сделала только навигацию. Ниже ты как раз предлагаешь мне их обернуть.

2021-08-01 20:11 UTC, EtelBogen commented on source/index.html
> +      <div class="page-header__wrapper page-header__wrapper--index">
Я думала на него повесить бэкграундом телефон с рукой. Я не уверена была, что это контентное изображение, но на внутренних страницах его нет, поэтому дополнительную обертку для бэкграунда. Или это излишне?

2021-08-01 20:11 UTC, EtelBogen commented on source/index.html
> +      <div class="page-header__wrapper page-header__wrapper--index">
Про навигацию и лого ответила выше. Да, так и сделаю.

2021-08-01 20:22 UTC, EtelBogen commented on source/index.html
> +    <main class="page-main page-main--index">
Ничего, сделала однообразно с хедером на автомате. Но вообще посмотрев внимательно, можно сразу убрать, чтобы не мешался. Нечего вешать на него.

2021-08-01 20:22 UTC, Manyaka commented on source/index.html
> +      <div class="page-header__wrapper page-header__wrapper--index">
Телефон с рукой можно было бы сделать мульти бекграундом. Но если будет сложно, воткнем див _потом_

2021-08-01 20:24 UTC, Manyaka commented on source/index.html
> +    <main class="page-main page-main--index">
да, и вообще, лучше потом, когда будешь делать цсс дописать классов и даже теги добавить, чем сразу делать. лишнее

2021-08-01 20:36 UTC, EtelBogen commented on source/index.html
> +          <h2 class="visually-hidden">Отзывы</h2>
Так, и тут я сделала, как показано было в лекции. А когда уже самостоятельно верстала контакты, то заголовок вынесла из обертки дива. То есть везде сделать так? Секция, внутри сначала заголовок, потом див-обертка?

2021-08-01 20:47 UTC, EtelBogen commented on source/index.html
> +          <ul class="reviews__list slider__list">
Конкретно вот слайдер — полностью взяла из лекции. С подобным миксованием. И кнопки ниже — тоже из лекции. И демонстрации. 
[2.8. Барбершоп. Разметка главной страницы по БЭМ](https://up.htmlacademy.ru/profession/frontender/11/adaptive/demos/5421) слайды 41-43
Там это объяснялось так: 
«Начнём миксовать слайдер. Слайдер будет заниматься визуальным расположением блоков преимуществ и листанием, которое будет реализовано с помощью JavaScript. Слайдер состоит из трёх частей:
    блок слайдера;
    список слайдов;
    слайд.
Примиксуем слайдер к преимуществам.
Список слайдов .slider__list примиксовываем к списку преимуществ.
А слайд (.slider__item) примиксовываем к преимуществу. Таким образом каждый блок занимается своим делом, и мы сможем переиспользовать слайдер».

Я так понимаю, что ты предлагаешь сделать список блоком со слайдами, а внутри каждого слайда сделать отдельный блок в виде отзыва? Честно говоря, так мне более понятно, чем когда один элемент един в двух лицах. Вот эта часть лекции мне как раз и взорвала мозг.

2021-08-01 20:51 UTC, EtelBogen commented on source/index.html
> +            </p>
Да, в лекции сказали делать параграфом. 
Черт, больше всего замечаний в тех местах, когда я сделала все, как было сказано в лекции :)

2021-08-01 20:57 UTC, EtelBogen commented on source/index.html
> +          <a class="copyright__link" href="https://htmlacademy.ru/intensive/adaptive" aria-label="HTML Academy">HTML Academy</a>
Переклинило. Это дублирование. Почему-то вот здесь мне уперлось сделать. Но да, дублирование.

2021-08-01 21:06 UTC, EtelBogen commented on source/index.html
> +        <section class="intro intro--index">
А как тогда сделать так, что на главной есть блок, которого нет во внутренних страницах? Он еще и видоизменяется в планшетной и десктопной версиях.

2021-08-02 07:58 UTC, Manyaka commented on source/index.html
> +          <h2 class="visually-hidden">Отзывы</h2>
у тебя див оберток нигде не будет

2021-08-02 08:32 UTC, Manyaka commented on source/index.html
> +          <ul class="reviews__list slider__list">
ну, посмотри как в демо - не два блока на одном теге, а на секшене один блок, на диве второй - так что в демо всё правильно. Но смысла так сейчас делать нет, дивы все лишние врапперы, тк всё прекрасно стилизуется с помощью секшенов и ul

2021-08-02 08:35 UTC, Manyaka commented on source/index.html
> +            </p>
ну не знаю (это я про лекции), бывает, студенты неверно понимают контекст, те в лекции всё правильно, но не в том контексте, который в домашке :)
Тут лучше див, тк параграф для текста, а тут текста нет - тут управляющие кнопки

2021-08-02 08:36 UTC, Manyaka commented on source/index.html
> +        <section class="intro intro--index">
див

2021-08-02 08:41 UTC, Manyaka commented on source/index.html
> +        <section class="intro intro--index">
секшн - это секционный блок 
![Снимок экрана 2021-08-02 в 11 40 02](https://user-images.githubusercontent.com/6417966/127831349-ecb630ff-6069-40db-903f-460431fb7049.jpg)
видишь, это блоки одного уровня, поэтому их, конечно, можно вкладывать в друг друга, но нет смысла

2021-08-04 08:18 UTC, EtelBogen commented on source/index.html
> +        </section>
Да, хочу бэкграундом, потому что по сути это декоративный элемент.

2021-08-13 05:18 UTC, merged